apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service
  labels: 
    app: echo-service
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: echo-service
  template:
    metadata:
      labels: 
        app: echo-service
    spec:
      containers:
      - name: echo-service
        image: registry.repo.services.lenvendo.ru:8443/grade-factor/echo
        ports:
        - containerPort: 8080
        - containerPort: 8181
      imagePullSecrets: 
      - name: registry-credentials
