apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LnJlcG8uc2VydmljZXMu
                     bGVudmVuZG8ucnU6ODQ0MyI6ewogICAgICAgICAgICAidXNlcm5hbWUiOiJ2X2FyYXNoaWgiLAog
                     ICAgICAgICAgICAicGFzc3dvcmQiOiJhcjN6SENwciIsCiAgICAgICAgICAgICJlbWFpbCI6InZh
                     ZGltLmFyYXNoaW5AbGVudmVuZG8ucnUiLAogICAgICAgICAgICAiYXV0aCI6IkJBU0VfNjRfQkFT
                     SUNfQVVUSF9DUkVERU5USUFMUyAoc2VlIGJlbG93KSIKCX0KICAgIH0KfQo=

