apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.applicationName }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName  }}
    spec:
      containers:
        - name: {{ .Values.applicationName }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
          - containerPort: {{ .Values.app.server.http.port }}
            name: http
          - containerPort:  {{ .Values.app.server.grpc.port }}
            name: grpc
          {{ if .Values.app.metrics.enabled }}
          - containerPort:  {{ .Values.app.metrics.port }}
          {{ end }}
          env:
            - name: "GCS_SERVER_HTTP_PORT"
              value: {{ .Values.app.server.http.port | quote }}
      nodeSelector:
        {{ .Values.nodeSelector.selector }}: {{ .Values.nodeSelector.selector }}
      imagePullSecrets:
        - name: regcred
