{{- define "config.env" -}}
{{ if .Values.app.config }}
- {{ template "builder.envvar.value" ( list ( printf "%s%s" ( .Values.app.envPrefix | default ( printf "%s_" ( .Chart.Name | upper ) ) ) "CONFIG" ) .Values.app.config ) }}
{{ end }}
{{ end }}
