{{- define "limiter.env" -}}
#метрики
{{ if .Values.app.limiter.enabled }}
- {{ template "builder.envvar.value" ( list ( printf "%s%s" ( .Values.app.envPrefix | default ( printf "%s_" ( .Chart.Name | upper ) ) ) "LIMITER_ENABLED" ) ( print .Values.app.limiter.enabled ) ) }}
- {{ template "builder.envvar.value" ( list ( printf "%s%s" ( .Values.app.envPrefix | default ( printf "%s_" ( .Chart.Name | upper ) ) ) "LIMITER_LIMIT" ) .Values.app.limiter.limit ) }}
{{- end -}}
{{- end -}}
