{{- define "logger.env" -}}
- {{ template "builder.envvar.value" ( list ( printf "%s%s" ( .Values.app.envPrefix | default ( printf "%s_" ( .Chart.Name | upper ) ) ) "LOGGER_LEVEL" ) .Values.app.logger.level ) }}
- {{ template "builder.envvar.value" ( list ( printf "%s%s" ( .Values.app.envPrefix | default ( printf "%s_" ( .Chart.Name | upper ) ) ) "LOGGER_TIME_FORMAT" ) .Values.app.logger.timeFormat ) }}
{{- end -}}
