{{- define "opentracing.env" -}}
#трассировщик
{{ if .Values.app.tracer.enabled }}
- {{ template "builder.envvar.value" ( list ( printf "%s%s" ( .Values.app.envPrefix | default ( printf "%s_" ( .Chart.Name | upper ) ) ) "TRACER_ENABLED" ) ( print .Values.app.tracer.enabled ) ) }}
- {{ template "builder.envvar.value" ( list ( printf "%s%s" ( .Values.app.envPrefix | default ( printf "%s_" ( .Chart.Name | upper ) ) ) "TRACER_NAME" ) ( .Values.app.tracer.name | default ( printf "%s-%s" .Release.Name .Release.Namespace ) ) ) }}
- {{ template "builder.envvar.value" ( list ( printf "%s%s" ( .Values.app.envPrefix | default ( printf "%s_" ( .Chart.Name | upper ) ) ) "TRACER_HOST" ) .Values.app.tracer.host ) }}
- {{ template "builder.envvar.value" ( list ( printf "%s%s" ( .Values.app.envPrefix | default ( printf "%s_" ( .Chart.Name | upper ) ) ) "TRACER_PORT" ) .Values.app.tracer.port ) }}
{{- end -}}
{{- end -}}
