{{- define "sentry.env" -}}
#sentry
{{ if .Values.app.sentry.enabled }}
- {{ template "builder.envvar.value" ( list ( printf "%s%s" ( .Values.app.envPrefix | default ( printf "%s_" ( .Chart.Name | upper ) ) ) "SENTRY_ENABLED" ) ( print .Values.app.sentry.enabled ) ) }}
- {{ template "builder.envvar.value" ( list ( printf "%s%s" ( .Values.app.envPrefix | default ( printf "%s_" ( .Chart.Name | upper ) ) ) "SENTRY_DSN" ) .Values.app.sentry.dsn ) }}
- {{ template "builder.envvar.value" ( list ( printf "%s%s" ( .Values.app.envPrefix | default ( printf "%s_" ( .Chart.Name | upper ) ) ) "SENTRY_ENVIRONMENT" ) ( .Values.app.sentry.environment | default "local" ) ) }}
{{- end -}}
{{- end -}}
